ARG BASE_IMAGE=
FROM ${BASE_IMAGE:-mcr.microsoft.com/devcontainers/base:2-jammy}

ARG NPM_CONFIG_REGISTRY=
ENV NPM_CONFIG_REGISTRY=${NPM_CONFIG_REGISTRY:-https://registry.npmjs.org/}

ARG PIP_INDEX_URL=
ENV PIP_INDEX_URL=${PIP_INDEX_URL:-https://pypi.org/simple/}

ARG UV_DEFAULT_INDEX=
ENV UV_DEFAULT_INDEX=${UV_DEFAULT_INDEX:-https://pypi.org/simple/}
